package cli

const ArcEntryStub = `// Code generated by arc build — do not edit.
package main

/*
#include <stdlib.h>
*/
import "C"
import "os"

//export AppMain
func AppMain(channelID *C.char) C.int {
	os.Args = append(os.Args, "--channel", C.GoString(channelID))
	main()
	return 1
}
`

type projectData struct {
	BinaryName     string
	LibArcName     string
	ModuleName     string
	LoadModulePath string
	LibArcInclude  string
	MainFile       string // "main.cpp" or "main.mm"
	BundleID       string // empty on non-Apple or when not set
}

const CMakeListsTmpl = `cmake_minimum_required(VERSION 3.22)
project({{.BinaryName}} LANGUAGES CXX OBJCXX)

set(CMAKE_CXX_STANDARD          20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS        OFF)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")

add_executable({{.BinaryName}} {{.MainFile}})

target_include_directories({{.BinaryName}} PRIVATE
    "${CMAKE_SOURCE_DIR}/{{.LibArcInclude}}"
)

target_link_libraries({{.BinaryName}} PRIVATE
    "${CMAKE_SOURCE_DIR}/{{.LibArcName}}"
)

if(APPLE)
    set_target_properties({{.BinaryName}} PROPERTIES
        INSTALL_RPATH "@executable_path"
        BUILD_RPATH   "@executable_path/../..")
elseif(UNIX)
    set_target_properties({{.BinaryName}} PROPERTIES
        INSTALL_RPATH "$ORIGIN"
        BUILD_RPATH   "$ORIGIN/../..")
endif()

add_custom_command(TARGET {{.BinaryName}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_SOURCE_DIR}/{{.LibArcName}}"
        "$<TARGET_FILE_DIR:{{.BinaryName}}>/{{.LibArcName}}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_SOURCE_DIR}/{{.ModuleName}}"
        "$<TARGET_FILE_DIR:{{.BinaryName}}>/{{.ModuleName}}"
    COMMENT "Copying shared libraries alongside {{.BinaryName}}"
)
`

// MainMmTmpl is used on macOS when arc.json supplies a bundle_id.
// The NSBundle setValue:forKey: call gives StoreKit a bundle identifier
// before arc::Run() touches the store daemon.
const MainMmTmpl = `#include <arc/arc.h>
#import <Foundation/Foundation.h>

int main() {
    [[NSBundle mainBundle] setValue:@"{{.BundleID}}"
                             forKey:@"CFBundleIdentifier"];
    arc::LoadModule("{{.LoadModulePath}}");
    arc::Run();
    return 0;
}
`

const MainCppTmpl = `#include <arc/arc.h>

int main() {
    arc::LoadModule("{{.LoadModulePath}}");
    arc::Run();
    return 0;
}
`