package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"

	gogit "github.com/go-git/go-git/v5"
)

const arcRepo = "https://github.com/carbon-os/arc"

const arcEntryStub = `// Code generated by arc build — do not edit.
package main

/*
#include <stdlib.h>
*/
import "C"
import "os"

//export AppMain
func AppMain(channelID *C.char) C.int {
	os.Args = append(os.Args, "--channel", C.GoString(channelID))
	main()
	return 1
}
`

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}
	switch os.Args[1] {
	case "build":
		if err := runBuild(os.Args[2:]); err != nil {
			fmt.Fprintf(os.Stderr, "\narc build: %v\n", err)
			os.Exit(1)
		}
	case "help", "--help", "-h":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "arc: unknown command %q\n\n", os.Args[1])
		usage()
		os.Exit(1)
	}
}

func usage() {
	fmt.Print(`arc — build tool for Arc applications

Usage:
  arc build [-o name] [go-build-flags] [package]

Commands:
  build     Clone and build libarc, compile your Go module as a shared
            library, and generate a ready-to-build arc-project/ directory.

Flags:
  -o name   Name of the final host binary (default: current directory name)

Any flags not listed above are forwarded to 'go build' unchanged.

Examples:
  arc build .
  arc build -o myapp .
  arc build -race -o myapp .

After running arc build:
  cd arc-project && cmake --build build
  — or open arc-project/ in Xcode for a native debug session
`)
}

// ── build config ──────────────────────────────────────────────────────────────

type buildConfig struct {
	binaryName string   // final host binary name (from -o, defaults to dir name)
	goFlags    []string // extra flags forwarded verbatim to go build
	goPackage  string   // package argument, defaults to "."

	wd         string // working directory at invocation time
	projectDir string // <wd>/arc-project/
	arcRepoDir string // <wd>/arc-project/arc-repo/         (full cloned repo)
	libarcDir  string // <wd>/arc-project/arc-repo/libarc/  (C++ source)
	moduleLib  string // <wd>/arc-project/libarc-module.{ext}
	libarcLib  string // <wd>/arc-project/{libarc.dylib|libarc.so|arc.dll}
	stubPath   string // <wd>/_arc_entry.go
}

func parseBuildArgs(args []string) (*buildConfig, error) {
	cfg := &buildConfig{goPackage: "."}

	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "-o" && i+1 < len(args):
			i++
			cfg.binaryName = args[i]
		case strings.HasPrefix(args[i], "-o="):
			cfg.binaryName = strings.TrimPrefix(args[i], "-o=")
		case !strings.HasPrefix(args[i], "-"):
			cfg.goPackage = args[i]
		default:
			cfg.goFlags = append(cfg.goFlags, args[i])
		}
	}

	wd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	cfg.wd = wd

	if cfg.binaryName == "" {
		cfg.binaryName = filepath.Base(wd)
	}

	cfg.projectDir = filepath.Join(wd, "arc-project")
	cfg.arcRepoDir = filepath.Join(cfg.projectDir, "arc-repo")
	cfg.libarcDir  = filepath.Join(cfg.arcRepoDir, "libarc")
	cfg.moduleLib  = filepath.Join(cfg.projectDir, "libarc-module"+sharedExt())
	cfg.libarcLib  = filepath.Join(cfg.projectDir, libarcFileName())
	cfg.stubPath   = filepath.Join(wd, "_arc_entry.go")

	return cfg, nil
}

// ── top-level orchestration ───────────────────────────────────────────────────

func runBuild(args []string) error {
	cfg, err := parseBuildArgs(args)
	if err != nil {
		return err
	}

	steps := []struct {
		label string
		fn    func(*buildConfig) error
	}{
		{"cloning libarc", stepCloneLibarc},
		{"building libarc", stepBuildLibarc},
		{"resolving Go dependencies", stepGoMod},
		{"compiling Go module", stepCompileGoModule},
		{"generating arc-project", stepGenerateProject},
		{"configuring cmake", stepConfigureCmake},
	}

	for _, s := range steps {
		fmt.Printf("\n▶  %s\n", s.label)
		if err := s.fn(cfg); err != nil {
			return fmt.Errorf("%s: %w", s.label, err)
		}
	}

	fmt.Printf("\n✅  arc-project/ is ready\n\n")
	fmt.Printf("   To build the final binary:\n")
	fmt.Printf("     cd arc-project && cmake --build build\n\n")
	fmt.Printf("   To debug natively:\n")
	fmt.Printf("     open arc-project/ in Xcode\n\n")
	return nil
}

// ── step 1: clone or update libarc ───────────────────────────────────────────

func stepCloneLibarc(cfg *buildConfig) error {
	if _, err := os.Stat(cfg.arcRepoDir); err == nil {
		fmt.Printf("   updating %s\n", arcRepo)
		repo, err := gogit.PlainOpen(cfg.arcRepoDir)
		if err != nil {
			return fmt.Errorf("open existing repo: %w", err)
		}
		wt, err := repo.Worktree()
		if err != nil {
			return err
		}
		err = wt.Pull(&gogit.PullOptions{RemoteName: "origin"})
		if err != nil && !errors.Is(err, gogit.NoErrAlreadyUpToDate) {
			return fmt.Errorf("pull: %w", err)
		}
		return nil
	}

	fmt.Printf("   downloading libarc from %s\n", arcRepo)
	if err := os.MkdirAll(cfg.projectDir, 0o755); err != nil {
		return err
	}
	_, err := gogit.PlainClone(cfg.arcRepoDir, false, &gogit.CloneOptions{
		URL:      arcRepo,
		Progress: os.Stderr,
		Depth:    1,
	})
	return err
}

// ── step 2: build libarc with cmake ──────────────────────────────────────────

func stepBuildLibarc(cfg *buildConfig) error {
	buildDir := filepath.Join(cfg.libarcDir, "build")
	if err := os.MkdirAll(buildDir, 0o755); err != nil {
		return err
	}

	configureArgs := []string{cfg.libarcDir, "-B", buildDir, "-DCMAKE_BUILD_TYPE=Release"}
	if runtime.GOOS == "windows" {
		vcpkg := os.Getenv("VCPKG_ROOT")
		if vcpkg == "" {
			return fmt.Errorf("VCPKG_ROOT is not set — required for Windows builds")
		}
		configureArgs = append(configureArgs,
			"-DCMAKE_TOOLCHAIN_FILE="+filepath.Join(vcpkg, "scripts", "buildsystems", "vcpkg.cmake"),
		)
	}
	fmt.Printf("   cmake configure\n")
	if err := runCmd(cfg.libarcDir, "cmake", configureArgs...); err != nil {
		return fmt.Errorf("cmake configure: %w", err)
	}

	fmt.Printf("   cmake build\n")
	if err := runCmd(cfg.libarcDir, "cmake", "--build", buildDir, "--config", "Release"); err != nil {
		return fmt.Errorf("cmake build: %w", err)
	}

	built, err := findBuiltLibarc(buildDir)
	if err != nil {
		return err
	}
	fmt.Printf("   copying %s → arc-project/%s\n", filepath.Base(built), filepath.Base(cfg.libarcLib))
	return copyFile(built, cfg.libarcLib)
}

func findBuiltLibarc(buildDir string) (string, error) {
	name := libarcFileName()
	candidates := []string{
		filepath.Join(buildDir, "lib", name),
		filepath.Join(buildDir, "lib", "Release", name),
		filepath.Join(buildDir, "Release", name),
		filepath.Join(buildDir, name),
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	return "", fmt.Errorf("%s not found — searched:\n  %s",
		name, strings.Join(candidates, "\n  "))
}

// ── step 3: ensure go.mod exists and dependencies are resolved ───────────────

func stepGoMod(cfg *buildConfig) error {
	goMod := filepath.Join(cfg.wd, "go.mod")
	if _, err := os.Stat(goMod); os.IsNotExist(err) {
		// Derive a simple module path from the binary name.
		modulePath := "app/" + cfg.binaryName
		fmt.Printf("   go mod init %s\n", modulePath)
		if err := runCmd(cfg.wd, "go", "mod", "init", modulePath); err != nil {
			return fmt.Errorf("go mod init: %w", err)
		}
	} else {
		fmt.Printf("   go.mod already exists, skipping init\n")
	}

	fmt.Printf("   go mod tidy\n")
	if err := runCmd(cfg.wd, "go", "mod", "tidy"); err != nil {
		return fmt.Errorf("go mod tidy: %w", err)
	}
	return nil
}

// ── step 4: compile Go module as shared library ───────────────────────────────

func stepCompileGoModule(cfg *buildConfig) error {
	fmt.Printf("   injecting _arc_entry.go\n")
	if err := os.WriteFile(cfg.stubPath, []byte(arcEntryStub), 0o644); err != nil {
		return fmt.Errorf("write stub: %w", err)
	}
	defer func() {
		fmt.Printf("   removing _arc_entry.go\n")
		os.Remove(cfg.stubPath)
	}()

	if err := os.MkdirAll(cfg.projectDir, 0o755); err != nil {
		return err
	}

	goArgs := []string{"build", "-buildmode=c-shared", "-o", cfg.moduleLib}
	goArgs = append(goArgs, cfg.goFlags...)
	goArgs = append(goArgs, cfg.goPackage)

	fmt.Printf("   go %s\n", strings.Join(goArgs, " "))
	return runCmd(cfg.wd, "go", goArgs...)
}

// ── step 5: generate CMakeLists.txt and main.cpp ─────────────────────────────

type projectData struct {
	BinaryName     string
	LibArcName     string // e.g. "libarc.dylib"
	ModuleName     string // e.g. "libarc-module.dylib"
	LoadModulePath string // argument passed to arc::LoadModule
	LibArcInclude  string // relative path from arc-project/ to libarc/include
}

const cmakeListsTmpl = `cmake_minimum_required(VERSION 3.22)
project({{.BinaryName}} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD          20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS        OFF)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")

add_executable({{.BinaryName}} main.cpp)

target_include_directories({{.BinaryName}} PRIVATE
    "${CMAKE_SOURCE_DIR}/{{.LibArcInclude}}"
)

target_link_libraries({{.BinaryName}} PRIVATE
    "${CMAKE_SOURCE_DIR}/{{.LibArcName}}"
)

if(APPLE)
    set_target_properties({{.BinaryName}} PROPERTIES
        INSTALL_RPATH "@executable_path"
        BUILD_RPATH   "@executable_path/../..")
elseif(UNIX)
    set_target_properties({{.BinaryName}} PROPERTIES
        INSTALL_RPATH "$ORIGIN"
        BUILD_RPATH   "$ORIGIN/../..")
endif()

add_custom_command(TARGET {{.BinaryName}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_SOURCE_DIR}/{{.LibArcName}}"
        "$<TARGET_FILE_DIR:{{.BinaryName}}>/{{.LibArcName}}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_SOURCE_DIR}/{{.ModuleName}}"
        "$<TARGET_FILE_DIR:{{.BinaryName}}>/{{.ModuleName}}"
    COMMENT "Copying shared libraries alongside {{.BinaryName}}"
)
`

const mainCppTmpl = `#include <arc/arc.h>

int main() {
    arc::LoadModule("{{.LoadModulePath}}");
    arc::Run();
    return 0;
}
`

func stepGenerateProject(cfg *buildConfig) error {
	data := projectData{
		BinaryName:     cfg.binaryName,
		LibArcName:     filepath.Base(cfg.libarcLib),
		ModuleName:     filepath.Base(cfg.moduleLib),
		LoadModulePath: loadModulePath(filepath.Base(cfg.moduleLib)),
		LibArcInclude:  filepath.ToSlash(filepath.Join("arc-repo", "libarc", "include")),
	}

	files := []struct {
		name string
		tmpl string
	}{
		{"CMakeLists.txt", cmakeListsTmpl},
		{"main.cpp", mainCppTmpl},
	}

	for _, f := range files {
		path := filepath.Join(cfg.projectDir, f.name)
		fmt.Printf("   writing arc-project/%s\n", f.name)
		t, err := template.New(f.name).Parse(f.tmpl)
		if err != nil {
			return fmt.Errorf("parse template %s: %w", f.name, err)
		}
		out, err := os.Create(path)
		if err != nil {
			return err
		}
		if err := t.Execute(out, data); err != nil {
			out.Close()
			return fmt.Errorf("render %s: %w", f.name, err)
		}
		out.Close()
	}
	return nil
}

func loadModulePath(moduleBase string) string {
	switch runtime.GOOS {
	case "darwin":
		return "@executable_path/" + moduleBase
	default:
		return moduleBase
	}
}

// ── step 6: pre-configure the cmake build tree ───────────────────────────────

func stepConfigureCmake(cfg *buildConfig) error {
	buildDir := filepath.Join(cfg.projectDir, "build")
	if err := os.MkdirAll(buildDir, 0o755); err != nil {
		return err
	}

	configureArgs := []string{cfg.projectDir, "-B", buildDir, "-DCMAKE_BUILD_TYPE=Release"}
	if runtime.GOOS == "windows" {
		if vcpkg := os.Getenv("VCPKG_ROOT"); vcpkg != "" {
			configureArgs = append(configureArgs,
				"-DCMAKE_TOOLCHAIN_FILE="+filepath.Join(vcpkg, "scripts", "buildsystems", "vcpkg.cmake"),
			)
		}
	}

	fmt.Printf("   cmake -B arc-project/build\n")
	return runCmd(cfg.projectDir, "cmake", configureArgs...)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func sharedExt() string {
	switch runtime.GOOS {
	case "darwin":
		return ".dylib"
	case "windows":
		return ".dll"
	default:
		return ".so"
	}
}

func libarcFileName() string {
	switch runtime.GOOS {
	case "windows":
		return "arc.dll"
	case "darwin":
		return "libarc.dylib"
	default:
		return "libarc.so"
	}
}

func runCmd(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}